using System.Collections.Generic;

namespace OrcaMDF.Core.MetaData.BaseTables
{
	/// <summary>
	/// TODO
	/// This one's a bit ugly. Doesn't use Columns like all others. Can't be parsed as values are stored in resourceDB, which we can't parse.
	/// Hardcoded values instead - will refactor eventually, to be more consistent.
	/// </summary>
	internal class syspalvalue : Row
	{
		private static readonly ISchema schema = new Schema(new DataColumn[0]);


		internal string @class { get; set; }
		internal int value { get; set; }
		internal string name { get; set; }

		public syspalvalue() : base(schema)
		{ }

		public override Row NewRow()
		{
			return new syspalvalue();
		}

		internal static IList<syspalvalue> GetServer2008R2HardcodedValues()
		{
			return new[]
			{
				new syspalvalue { @class = "ASPS", value = 1, name = "SAFE_ACCESS" },
				new syspalvalue { @class = "ASPS", value = 2, name = "EXTERNAL_ACCESS" },
				new syspalvalue { @class = "ASPS", value = 3, name = "UNSAFE_ACCESS" },
				new syspalvalue { @class = "AUSD", value = 0, name = "CONTINUE" },
				new syspalvalue { @class = "AUSD", value = 1, name = "SHUTDOWN SERVER INSTANCE" },
				new syspalvalue { @class = "AUTY", value = 0, name = "DROPPED" },
				new syspalvalue { @class = "AUTY", value = 1, name = "IN_ROW_DATA" },
				new syspalvalue { @class = "AUTY", value = 2, name = "LOB_DATA" },
				new syspalvalue { @class = "AUTY", value = 3, name = "ROW_OVERFLOW_DATA" },
				new syspalvalue { @class = "BDTY", value = 2, name = "DISK" },
				new syspalvalue { @class = "BDTY", value = 3, name = "DISKETTE" },
				new syspalvalue { @class = "BDTY", value = 5, name = "TAPE" },
				new syspalvalue { @class = "BDTY", value = 6, name = "PIPE" },
				new syspalvalue { @class = "BDTY", value = 7, name = "VIRTUAL_DEVICE" },
				new syspalvalue { @class = "BDTY", value = 8, name = "REPLICA_DEVICE" },
				new syspalvalue { @class = "CMPL", value = 0, name = "NONE" },
				new syspalvalue { @class = "CMPL", value = 1, name = "ROW" },
				new syspalvalue { @class = "CMPL", value = 2, name = "PAGE" },
				new syspalvalue { @class = "CPKP", value = 6, name = "CRYPTOGRAPHIC PROVIDER" },
				new syspalvalue { @class = "CTRP", value = 1, name = "MINUTES" },
				new syspalvalue { @class = "CTRP", value = 2, name = "HOURS" },
				new syspalvalue { @class = "CTRP", value = 3, name = "DAYS" },
				new syspalvalue { @class = "DBFS", value = 0, name = "ONLINE" },
				new syspalvalue { @class = "DBFS", value = 1, name = "OFFLINE" },
				new syspalvalue { @class = "DBFS", value = 2, name = "OFFLINE" },
				new syspalvalue { @class = "DBFS", value = 3, name = "OFFLINE" },
				new syspalvalue { @class = "DBFS", value = 4, name = "DEFUNCT" },
				new syspalvalue { @class = "DBFS", value = 5, name = "RECOVERY_PENDING" },
				new syspalvalue { @class = "DBFS", value = 6, name = "OFFLINE" },
				new syspalvalue { @class = "DBFS", value = 7, name = "RESTORING" },
				new syspalvalue { @class = "DBFS", value = 8, name = "RESTORING" },
				new syspalvalue { @class = "DBFS", value = 9, name = "RECOVERY_PENDING" },
				new syspalvalue { @class = "DBFS", value = 10, name = "ONLINE" },
				new syspalvalue { @class = "DBFS", value = 11, name = "RESTORING" },
				new syspalvalue { @class = "DBFS", value = 12, name = "SUSPECT" },
				new syspalvalue { @class = "DBFT", value = 0, name = "ROWS" },
				new syspalvalue { @class = "DBFT", value = 1, name = "LOG" },
				new syspalvalue { @class = "DBFT", value = 2, name = "FILESTREAM" },
				new syspalvalue { @class = "DBFT", value = 3, name = "FILESTREAM_LOG" },
				new syspalvalue { @class = "DBFT", value = 4, name = "FULLTEXT" },
				new syspalvalue { @class = "DBPV", value = 0, name = "NONE" },
				new syspalvalue { @class = "DBPV", value = 1, name = "TORN_PAGE_DETECTION" },
				new syspalvalue { @class = "DBPV", value = 2, name = "CHECKSUM" },
				new syspalvalue { @class = "DBRO", value = 1, name = "FULL" },
				new syspalvalue { @class = "DBRO", value = 2, name = "BULK_LOGGED" },
				new syspalvalue { @class = "DBRO", value = 3, name = "SIMPLE" },
				new syspalvalue { @class = "DBSI", value = 0, name = "OFF" },
				new syspalvalue { @class = "DBSI", value = 1, name = "ON" },
				new syspalvalue { @class = "DBSI", value = 2, name = "IN_TRANSITION_TO_OFF" },
				new syspalvalue { @class = "DBSI", value = 3, name = "IN_TRANSITION_TO_ON" },
				new syspalvalue { @class = "DBSL", value = 0, name = "UNKNOWN" },
				new syspalvalue { @class = "DBSL", value = 1, name = "OFF" },
				new syspalvalue { @class = "DBSL", value = 2, name = "FULL" },
				new syspalvalue { @class = "DBST", value = 0, name = "ONLINE" },
				new syspalvalue { @class = "DBST", value = 1, name = "RESTORING" },
				new syspalvalue { @class = "DBST", value = 2, name = "RECOVERING" },
				new syspalvalue { @class = "DBST", value = 3, name = "RECOVERY_PENDING" },
				new syspalvalue { @class = "DBST", value = 4, name = "SUSPECT" },
				new syspalvalue { @class = "DBST", value = 5, name = "EMERGENCY" },
				new syspalvalue { @class = "DBST", value = 6, name = "OFFLINE" },
				new syspalvalue { @class = "DBST", value = 7, name = "DEFUNCT" },
				new syspalvalue { @class = "DBUA", value = 0, name = "MULTI_USER" },
				new syspalvalue { @class = "DBUA", value = 1, name = "SINGLE_USER" },
				new syspalvalue { @class = "DBUA", value = 2, name = "RESTRICTED_USER" },
				new syspalvalue { @class = "DPCL", value = 0, name = "OBJECT_OR_COLUMN_REFERENCE_NON_SCHEMA_BOUND" },
				new syspalvalue { @class = "DPCL", value = 1, name = "OBJECT_OR_COLUMN_REFERENCE_SCHEMA_BOUND" },
				new syspalvalue { @class = "DPCL", value = 2, name = "TYPE_REFERENCE" },
				new syspalvalue { @class = "DPCL", value = 3, name = "XML_SCHEMA_COLLECTION_REFERENCE" },
				new syspalvalue { @class = "DPCL", value = 4, name = "PARTITION_FUNCTION_REFERENCE" },
				new syspalvalue { @class = "EISD", value = 1, name = "LOW" },
				new syspalvalue { @class = "EISD", value = 2, name = "LOW" },
				new syspalvalue { @class = "EISD", value = 3, name = "MEDIUM" },
				new syspalvalue { @class = "EISD", value = 4, name = "HIGH" },
				new syspalvalue { @class = "EISP", value = 1, name = "GEOMETRY_GRID" },
				new syspalvalue { @class = "EISP", value = 2, name = "GEOGRAPHY_GRID" },
				new syspalvalue { @class = "EITP", value = 1, name = "GEOMETRY" },
				new syspalvalue { @class = "EITP", value = 2, name = "GEOGRAPHY" },
				new syspalvalue { @class = "EPCA", value = 0, name = "NONE" },
				new syspalvalue { @class = "EPCA", value = 1, name = "NTLM" },
				new syspalvalue { @class = "EPCA", value = 2, name = "KERBEROS" },
				new syspalvalue { @class = "EPCA", value = 3, name = "NEGOTIATE" },
				new syspalvalue { @class = "EPCA", value = 4, name = "CERTIFICATE" },
				new syspalvalue { @class = "EPCA", value = 5, name = "NTLM, CERTIFICATE" },
				new syspalvalue { @class = "EPCA", value = 6, name = "KERBEROS, CERTIFICATE" },
				new syspalvalue { @class = "EPCA", value = 7, name = "NEGOTIATE, CERTIFICATE" },
				new syspalvalue { @class = "EPCA", value = 8, name = "CERTIFICATE, NTLM" },
				new syspalvalue { @class = "EPCA", value = 9, name = "CERTIFICATE, KERBEROS" },
				new syspalvalue { @class = "EPCA", value = 10, name = "CERTIFICATE, NEGOTIATE" },
				new syspalvalue { @class = "EPCE", value = 0, name = "NONE" },
				new syspalvalue { @class = "EPCE", value = 1, name = "RC4" },
				new syspalvalue { @class = "EPCE", value = 2, name = "AES" },
				new syspalvalue { @class = "EPCE", value = 3, name = "NONE, RC4" },
				new syspalvalue { @class = "EPCE", value = 4, name = "NONE, AES" },
				new syspalvalue { @class = "EPCE", value = 5, name = "RC4, AES" },
				new syspalvalue { @class = "EPCE", value = 6, name = "AES, RC4" },
				new syspalvalue { @class = "EPCE", value = 7, name = "NONE, RC4, AES" },
				new syspalvalue { @class = "EPCE", value = 8, name = "NONE, AES, RC4" },
				new syspalvalue { @class = "EPCS", value = 0, name = "" },
				new syspalvalue { @class = "EPCS", value = 1, name = "INITIAL" },
				new syspalvalue { @class = "EPCS", value = 2, name = "CONNECTING" },
				new syspalvalue { @class = "EPCS", value = 3, name = "CONNECTED" },
				new syspalvalue { @class = "EPCS", value = 4, name = "LOGGED IN" },
				new syspalvalue { @class = "EPCS", value = 5, name = "CLOSED" },
				new syspalvalue { @class = "EPET", value = 0, name = "" },
				new syspalvalue { @class = "EPET", value = 1, name = "SIGNING ONLY" },
				new syspalvalue { @class = "EPET", value = 2, name = "RC4" },
				new syspalvalue { @class = "EPET", value = 3, name = "AES" },
				new syspalvalue { @class = "EPLS", value = 0, name = "INITIAL" },
				new syspalvalue { @class = "EPLS", value = 1, name = "WAIT LOGIN NEGOTIATE" },
				new syspalvalue { @class = "EPLS", value = 2, name = "ONE ISC" },
				new syspalvalue { @class = "EPLS", value = 3, name = "ONE ASC" },
				new syspalvalue { @class = "EPLS", value = 4, name = "TWO ISC" },
				new syspalvalue { @class = "EPLS", value = 5, name = "TWO ASC" },
				new syspalvalue { @class = "EPLS", value = 6, name = "WAIT ISC Confirm" },
				new syspalvalue { @class = "EPLS", value = 7, name = "WAIT ASC Confirm" },
				new syspalvalue { @class = "EPLS", value = 8, name = "WAIT REJECT" },
				new syspalvalue { @class = "EPLS", value = 9, name = "WAIT PRE-MASTER SECRET" },
				new syspalvalue { @class = "EPLS", value = 10, name = "WAIT VALIDATION" },
				new syspalvalue { @class = "EPLS", value = 11, name = "WAIT ARBITRATION" },
				new syspalvalue { @class = "EPLS", value = 12, name = "ONLINE" },
				new syspalvalue { @class = "EPLS", value = 13, name = "ERROR" },
				new syspalvalue { @class = "EPMR", value = 0, name = "NONE" },
				new syspalvalue { @class = "EPMR", value = 1, name = "PARTNER" },
				new syspalvalue { @class = "EPMR", value = 2, name = "WITNESS" },
				new syspalvalue { @class = "EPMR", value = 3, name = "ALL" },
				new syspalvalue { @class = "EPPR", value = 1, name = "HTTP" },
				new syspalvalue { @class = "EPPR", value = 2, name = "TCP" },
				new syspalvalue { @class = "EPPR", value = 3, name = "NAMED_PIPES" },
				new syspalvalue { @class = "EPPR", value = 4, name = "SHARED_MEMORY" },
				new syspalvalue { @class = "EPPR", value = 5, name = "VIA" },
				new syspalvalue { @class = "EPST", value = 0, name = "STARTED" },
				new syspalvalue { @class = "EPST", value = 1, name = "STOPPED" },
				new syspalvalue { @class = "EPST", value = 2, name = "DISABLED" },
				new syspalvalue { @class = "EPTY", value = 1, name = "SOAP" },
				new syspalvalue { @class = "EPTY", value = 2, name = "TSQL" },
				new syspalvalue { @class = "EPTY", value = 3, name = "SERVICE_BROKER" },
				new syspalvalue { @class = "EPTY", value = 4, name = "DATABASE_MIRRORING" },
				new syspalvalue { @class = "EVTY", value = 1, name = "INSERT" },
				new syspalvalue { @class = "EVTY", value = 2, name = "UPDATE" },
				new syspalvalue { @class = "EVTY", value = 3, name = "DELETE" },
				new syspalvalue { @class = "EVTY", value = 21, name = "CREATE_TABLE" },
				new syspalvalue { @class = "EVTY", value = 22, name = "ALTER_TABLE" },
				new syspalvalue { @class = "EVTY", value = 23, name = "DROP_TABLE" },
				new syspalvalue { @class = "EVTY", value = 24, name = "CREATE_INDEX" },
				new syspalvalue { @class = "EVTY", value = 25, name = "ALTER_INDEX" },
				new syspalvalue { @class = "EVTY", value = 26, name = "DROP_INDEX" },
				new syspalvalue { @class = "EVTY", value = 27, name = "CREATE_STATISTICS" },
				new syspalvalue { @class = "EVTY", value = 28, name = "UPDATE_STATISTICS" },
				new syspalvalue { @class = "EVTY", value = 29, name = "DROP_STATISTICS" },
				new syspalvalue { @class = "EVTY", value = 34, name = "CREATE_SYNONYM" },
				new syspalvalue { @class = "EVTY", value = 36, name = "DROP_SYNONYM" },
				new syspalvalue { @class = "EVTY", value = 41, name = "CREATE_VIEW" },
				new syspalvalue { @class = "EVTY", value = 42, name = "ALTER_VIEW" },
				new syspalvalue { @class = "EVTY", value = 43, name = "DROP_VIEW" },
				new syspalvalue { @class = "EVTY", value = 51, name = "CREATE_PROCEDURE" },
				new syspalvalue { @class = "EVTY", value = 52, name = "ALTER_PROCEDURE" },
				new syspalvalue { @class = "EVTY", value = 53, name = "DROP_PROCEDURE" },
				new syspalvalue { @class = "EVTY", value = 61, name = "CREATE_FUNCTION" },
				new syspalvalue { @class = "EVTY", value = 62, name = "ALTER_FUNCTION" },
				new syspalvalue { @class = "EVTY", value = 63, name = "DROP_FUNCTION" },
				new syspalvalue { @class = "EVTY", value = 71, name = "CREATE_TRIGGER" },
				new syspalvalue { @class = "EVTY", value = 72, name = "ALTER_TRIGGER" },
				new syspalvalue { @class = "EVTY", value = 73, name = "DROP_TRIGGER" },
				new syspalvalue { @class = "EVTY", value = 74, name = "CREATE_EVENT_NOTIFICATION" },
				new syspalvalue { @class = "EVTY", value = 76, name = "DROP_EVENT_NOTIFICATION" },
				new syspalvalue { @class = "EVTY", value = 91, name = "CREATE_TYPE" },
				new syspalvalue { @class = "EVTY", value = 93, name = "DROP_TYPE" },
				new syspalvalue { @class = "EVTY", value = 101, name = "CREATE_ASSEMBLY" },
				new syspalvalue { @class = "EVTY", value = 102, name = "ALTER_ASSEMBLY" },
				new syspalvalue { @class = "EVTY", value = 103, name = "DROP_ASSEMBLY" },
				new syspalvalue { @class = "EVTY", value = 131, name = "CREATE_USER" },
				new syspalvalue { @class = "EVTY", value = 132, name = "ALTER_USER" },
				new syspalvalue { @class = "EVTY", value = 133, name = "DROP_USER" },
				new syspalvalue { @class = "EVTY", value = 134, name = "CREATE_ROLE" },
				new syspalvalue { @class = "EVTY", value = 135, name = "ALTER_ROLE" },
				new syspalvalue { @class = "EVTY", value = 136, name = "DROP_ROLE" },
				new syspalvalue { @class = "EVTY", value = 137, name = "CREATE_APPLICATION_ROLE" },
				new syspalvalue { @class = "EVTY", value = 138, name = "ALTER_APPLICATION_ROLE" },
				new syspalvalue { @class = "EVTY", value = 139, name = "DROP_APPLICATION_ROLE" },
				new syspalvalue { @class = "EVTY", value = 141, name = "CREATE_SCHEMA" },
				new syspalvalue { @class = "EVTY", value = 142, name = "ALTER_SCHEMA" },
				new syspalvalue { @class = "EVTY", value = 143, name = "DROP_SCHEMA" },
				new syspalvalue { @class = "EVTY", value = 144, name = "CREATE_LOGIN" },
				new syspalvalue { @class = "EVTY", value = 145, name = "ALTER_LOGIN" },
				new syspalvalue { @class = "EVTY", value = 146, name = "DROP_LOGIN" },
				new syspalvalue { @class = "EVTY", value = 147, name = "LOGON" },
				new syspalvalue { @class = "EVTY", value = 151, name = "CREATE_MESSAGE_TYPE" },
				new syspalvalue { @class = "EVTY", value = 152, name = "ALTER_MESSAGE_TYPE" },
				new syspalvalue { @class = "EVTY", value = 153, name = "DROP_MESSAGE_TYPE" },
				new syspalvalue { @class = "EVTY", value = 154, name = "CREATE_CONTRACT" },
				new syspalvalue { @class = "EVTY", value = 156, name = "DROP_CONTRACT" },
				new syspalvalue { @class = "EVTY", value = 157, name = "CREATE_QUEUE" },
				new syspalvalue { @class = "EVTY", value = 158, name = "ALTER_QUEUE" },
				new syspalvalue { @class = "EVTY", value = 159, name = "DROP_QUEUE" },
				new syspalvalue { @class = "EVTY", value = 160, name = "BROKER_QUEUE_DISABLED" },
				new syspalvalue { @class = "EVTY", value = 161, name = "CREATE_SERVICE" },
				new syspalvalue { @class = "EVTY", value = 162, name = "ALTER_SERVICE" },
				new syspalvalue { @class = "EVTY", value = 163, name = "DROP_SERVICE" },
				new syspalvalue { @class = "EVTY", value = 164, name = "CREATE_ROUTE" },
				new syspalvalue { @class = "EVTY", value = 165, name = "ALTER_ROUTE" },
				new syspalvalue { @class = "EVTY", value = 166, name = "DROP_ROUTE" },
				new syspalvalue { @class = "EVTY", value = 167, name = "GRANT_SERVER" },
				new syspalvalue { @class = "EVTY", value = 168, name = "DENY_SERVER" },
				new syspalvalue { @class = "EVTY", value = 169, name = "REVOKE_SERVER" },
				new syspalvalue { @class = "EVTY", value = 170, name = "GRANT_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 171, name = "DENY_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 172, name = "REVOKE_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 173, name = "QUEUE_ACTIVATION" },
				new syspalvalue { @class = "EVTY", value = 174, name = "CREATE_REMOTE_SERVICE_BINDING" },
				new syspalvalue { @class = "EVTY", value = 175, name = "ALTER_REMOTE_SERVICE_BINDING" },
				new syspalvalue { @class = "EVTY", value = 176, name = "DROP_REMOTE_SERVICE_BINDING" },
				new syspalvalue { @class = "EVTY", value = 177, name = "CREATE_XML_SCHEMA_COLLECTION" },
				new syspalvalue { @class = "EVTY", value = 178, name = "ALTER_XML_SCHEMA_COLLECTION" },
				new syspalvalue { @class = "EVTY", value = 179, name = "DROP_XML_SCHEMA_COLLECTION" },
				new syspalvalue { @class = "EVTY", value = 181, name = "CREATE_ENDPOINT" },
				new syspalvalue { @class = "EVTY", value = 182, name = "ALTER_ENDPOINT" },
				new syspalvalue { @class = "EVTY", value = 183, name = "DROP_ENDPOINT" },
				new syspalvalue { @class = "EVTY", value = 191, name = "CREATE_PARTITION_FUNCTION" },
				new syspalvalue { @class = "EVTY", value = 192, name = "ALTER_PARTITION_FUNCTION" },
				new syspalvalue { @class = "EVTY", value = 193, name = "DROP_PARTITION_FUNCTION" },
				new syspalvalue { @class = "EVTY", value = 194, name = "CREATE_PARTITION_SCHEME" },
				new syspalvalue { @class = "EVTY", value = 195, name = "ALTER_PARTITION_SCHEME" },
				new syspalvalue { @class = "EVTY", value = 196, name = "DROP_PARTITION_SCHEME" },
				new syspalvalue { @class = "EVTY", value = 197, name = "CREATE_CERTIFICATE" },
				new syspalvalue { @class = "EVTY", value = 198, name = "ALTER_CERTIFICATE" },
				new syspalvalue { @class = "EVTY", value = 199, name = "DROP_CERTIFICATE" },
				new syspalvalue { @class = "EVTY", value = 201, name = "CREATE_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 202, name = "ALTER_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 203, name = "DROP_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 204, name = "ALTER_AUTHORIZATION_SERVER" },
				new syspalvalue { @class = "EVTY", value = 205, name = "ALTER_AUTHORIZATION_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 206, name = "CREATE_XML_INDEX" },
				new syspalvalue { @class = "EVTY", value = 207, name = "ADD_ROLE_MEMBER" },
				new syspalvalue { @class = "EVTY", value = 208, name = "DROP_ROLE_MEMBER" },
				new syspalvalue { @class = "EVTY", value = 209, name = "ADD_SERVER_ROLE_MEMBER" },
				new syspalvalue { @class = "EVTY", value = 210, name = "DROP_SERVER_ROLE_MEMBER" },
				new syspalvalue { @class = "EVTY", value = 211, name = "ALTER_EXTENDED_PROPERTY" },
				new syspalvalue { @class = "EVTY", value = 212, name = "ALTER_FULLTEXT_CATALOG" },
				new syspalvalue { @class = "EVTY", value = 213, name = "ALTER_FULLTEXT_INDEX" },
				new syspalvalue { @class = "EVTY", value = 214, name = "ALTER_INSTANCE" },
				new syspalvalue { @class = "EVTY", value = 215, name = "ALTER_MESSAGE" },
				new syspalvalue { @class = "EVTY", value = 216, name = "ALTER_PLAN_GUIDE" },
				new syspalvalue { @class = "EVTY", value = 217, name = "ALTER_REMOTE_SERVER" },
				new syspalvalue { @class = "EVTY", value = 218, name = "BIND_DEFAULT" },
				new syspalvalue { @class = "EVTY", value = 219, name = "BIND_RULE" },
				new syspalvalue { @class = "EVTY", value = 220, name = "CREATE_DEFAULT" },
				new syspalvalue { @class = "EVTY", value = 221, name = "CREATE_EXTENDED_PROCEDURE" },
				new syspalvalue { @class = "EVTY", value = 222, name = "CREATE_EXTENDED_PROPERTY" },
				new syspalvalue { @class = "EVTY", value = 223, name = "CREATE_FULLTEXT_CATALOG" },
				new syspalvalue { @class = "EVTY", value = 224, name = "CREATE_FULLTEXT_INDEX" },
				new syspalvalue { @class = "EVTY", value = 225, name = "CREATE_LINKED_SERVER" },
				new syspalvalue { @class = "EVTY", value = 226, name = "CREATE_LINKED_SERVER_LOGIN" },
				new syspalvalue { @class = "EVTY", value = 227, name = "CREATE_MESSAGE" },
				new syspalvalue { @class = "EVTY", value = 228, name = "CREATE_PLAN_GUIDE" },
				new syspalvalue { @class = "EVTY", value = 229, name = "CREATE_RULE" },
				new syspalvalue { @class = "EVTY", value = 230, name = "CREATE_REMOTE_SERVER" },
				new syspalvalue { @class = "EVTY", value = 231, name = "DROP_DEFAULT" },
				new syspalvalue { @class = "EVTY", value = 232, name = "DROP_EXTENDED_PROCEDURE" },
				new syspalvalue { @class = "EVTY", value = 233, name = "DROP_EXTENDED_PROPERTY" },
				new syspalvalue { @class = "EVTY", value = 234, name = "DROP_FULLTEXT_CATALOG" },
				new syspalvalue { @class = "EVTY", value = 235, name = "DROP_FULLTEXT_INDEX" },
				new syspalvalue { @class = "EVTY", value = 236, name = "DROP_LINKED_SERVER_LOGIN" },
				new syspalvalue { @class = "EVTY", value = 237, name = "DROP_MESSAGE" },
				new syspalvalue { @class = "EVTY", value = 238, name = "DROP_PLAN_GUIDE" },
				new syspalvalue { @class = "EVTY", value = 239, name = "DROP_RULE" },
				new syspalvalue { @class = "EVTY", value = 240, name = "DROP_REMOTE_SERVER" },
				new syspalvalue { @class = "EVTY", value = 241, name = "RENAME" },
				new syspalvalue { @class = "EVTY", value = 242, name = "UNBIND_DEFAULT" },
				new syspalvalue { @class = "EVTY", value = 243, name = "UNBIND_RULE" },
				new syspalvalue { @class = "EVTY", value = 244, name = "CREATE_SYMMETRIC_KEY" },
				new syspalvalue { @class = "EVTY", value = 245, name = "ALTER_SYMMETRIC_KEY" },
				new syspalvalue { @class = "EVTY", value = 246, name = "DROP_SYMMETRIC_KEY" },
				new syspalvalue { @class = "EVTY", value = 247, name = "CREATE_ASYMMETRIC_KEY" },
				new syspalvalue { @class = "EVTY", value = 248, name = "ALTER_ASYMMETRIC_KEY" },
				new syspalvalue { @class = "EVTY", value = 249, name = "DROP_ASYMMETRIC_KEY" },
				new syspalvalue { @class = "EVTY", value = 251, name = "ALTER_SERVICE_MASTER_KEY" },
				new syspalvalue { @class = "EVTY", value = 252, name = "CREATE_MASTER_KEY" },
				new syspalvalue { @class = "EVTY", value = 253, name = "ALTER_MASTER_KEY" },
				new syspalvalue { @class = "EVTY", value = 254, name = "DROP_MASTER_KEY" },
				new syspalvalue { @class = "EVTY", value = 255, name = "ADD_SIGNATURE_SCHEMA_OBJECT" },
				new syspalvalue { @class = "EVTY", value = 256, name = "DROP_SIGNATURE_SCHEMA_OBJECT" },
				new syspalvalue { @class = "EVTY", value = 257, name = "ADD_SIGNATURE" },
				new syspalvalue { @class = "EVTY", value = 258, name = "DROP_SIGNATURE" },
				new syspalvalue { @class = "EVTY", value = 259, name = "CREATE_CREDENTIAL" },
				new syspalvalue { @class = "EVTY", value = 260, name = "ALTER_CREDENTIAL" },
				new syspalvalue { @class = "EVTY", value = 261, name = "DROP_CREDENTIAL" },
				new syspalvalue { @class = "EVTY", value = 262, name = "DROP_LINKED_SERVER" },
				new syspalvalue { @class = "EVTY", value = 263, name = "ALTER_LINKED_SERVER" },
				new syspalvalue { @class = "EVTY", value = 264, name = "CREATE_EVENT_SESSION" },
				new syspalvalue { @class = "EVTY", value = 265, name = "ALTER_EVENT_SESSION" },
				new syspalvalue { @class = "EVTY", value = 266, name = "DROP_EVENT_SESSION" },
				new syspalvalue { @class = "EVTY", value = 267, name = "CREATE_RESOURCE_POOL" },
				new syspalvalue { @class = "EVTY", value = 268, name = "ALTER_RESOURCE_POOL" },
				new syspalvalue { @class = "EVTY", value = 269, name = "DROP_RESOURCE_POOL" },
				new syspalvalue { @class = "EVTY", value = 270, name = "CREATE_WORKLOAD_GROUP" },
				new syspalvalue { @class = "EVTY", value = 271, name = "ALTER_WORKLOAD_GROUP" },
				new syspalvalue { @class = "EVTY", value = 272, name = "DROP_WORKLOAD_GROUP" },
				new syspalvalue { @class = "EVTY", value = 273, name = "ALTER_RESOURCE_GOVERNOR_CONFIG" },
				new syspalvalue { @class = "EVTY", value = 274, name = "CREATE_SPATIAL_INDEX" },
				new syspalvalue { @class = "EVTY", value = 275, name = "CREATE_CRYPTOGRAPHIC_PROVIDER" },
				new syspalvalue { @class = "EVTY", value = 276, name = "ALTER_CRYPTOGRAPHIC_PROVIDER" },
				new syspalvalue { @class = "EVTY", value = 277, name = "DROP_CRYPTOGRAPHIC_PROVIDER" },
				new syspalvalue { @class = "EVTY", value = 278, name = "CREATE_DATABASE_ENCRYPTION_KEY" },
				new syspalvalue { @class = "EVTY", value = 279, name = "ALTER_DATABASE_ENCRYPTION_KEY" },
				new syspalvalue { @class = "EVTY", value = 280, name = "DROP_DATABASE_ENCRYPTION_KEY" },
				new syspalvalue { @class = "EVTY", value = 281, name = "CREATE_BROKER_PRIORITY" },
				new syspalvalue { @class = "EVTY", value = 282, name = "ALTER_BROKER_PRIORITY" },
				new syspalvalue { @class = "EVTY", value = 283, name = "DROP_BROKER_PRIORITY" },
				new syspalvalue { @class = "EVTY", value = 284, name = "CREATE_SERVER_AUDIT" },
				new syspalvalue { @class = "EVTY", value = 285, name = "ALTER_SERVER_AUDIT" },
				new syspalvalue { @class = "EVTY", value = 286, name = "DROP_SERVER_AUDIT" },
				new syspalvalue { @class = "EVTY", value = 287, name = "CREATE_SERVER_AUDIT_SPECIFICATION" },
				new syspalvalue { @class = "EVTY", value = 288, name = "ALTER_SERVER_AUDIT_SPECIFICATION" },
				new syspalvalue { @class = "EVTY", value = 289, name = "DROP_SERVER_AUDIT_SPECIFICATION" },
				new syspalvalue { @class = "EVTY", value = 290, name = "CREATE_DATABASE_AUDIT_SPECIFICATION" },
				new syspalvalue { @class = "EVTY", value = 291, name = "ALTER_DATABASE_AUDIT_SPECIFICATION" },
				new syspalvalue { @class = "EVTY", value = 292, name = "DROP_DATABASE_AUDIT_SPECIFICATION" },
				new syspalvalue { @class = "EVTY", value = 293, name = "CREATE_FULLTEXT_STOPLIST" },
				new syspalvalue { @class = "EVTY", value = 294, name = "ALTER_FULLTEXT_STOPLIST" },
				new syspalvalue { @class = "EVTY", value = 295, name = "DROP_FULLTEXT_STOPLIST" },
				new syspalvalue { @class = "EVTY", value = 296, name = "ALTER_SERVER_CONFIGURATION" },
				new syspalvalue { @class = "EVTY", value = 1014, name = "AUDIT_LOGIN" },
				new syspalvalue { @class = "EVTY", value = 1015, name = "AUDIT_LOGOUT" },
				new syspalvalue { @class = "EVTY", value = 1020, name = "AUDIT_LOGIN_FAILED" },
				new syspalvalue { @class = "EVTY", value = 1021, name = "EVENTLOG" },
				new syspalvalue { @class = "EVTY", value = 1022, name = "ERRORLOG" },
				new syspalvalue { @class = "EVTY", value = 1025, name = "LOCK_DEADLOCK" },
				new syspalvalue { @class = "EVTY", value = 1033, name = "EXCEPTION" },
				new syspalvalue { @class = "EVTY", value = 1034, name = "SP_CACHEMISS" },
				new syspalvalue { @class = "EVTY", value = 1035, name = "SP_CACHEINSERT" },
				new syspalvalue { @class = "EVTY", value = 1036, name = "SP_CACHEREMOVE" },
				new syspalvalue { @class = "EVTY", value = 1037, name = "SP_RECOMPILE" },
				new syspalvalue { @class = "EVTY", value = 1046, name = "OBJECT_CREATED" },
				new syspalvalue { @class = "EVTY", value = 1047, name = "OBJECT_DELETED" },
				new syspalvalue { @class = "EVTY", value = 1055, name = "HASH_WARNING" },
				new syspalvalue { @class = "EVTY", value = 1059, name = "LOCK_DEADLOCK_CHAIN" },
				new syspalvalue { @class = "EVTY", value = 1060, name = "LOCK_ESCALATION" },
				new syspalvalue { @class = "EVTY", value = 1061, name = "OLEDB_ERRORS" },
				new syspalvalue { @class = "EVTY", value = 1067, name = "EXECUTION_WARNINGS" },
				new syspalvalue { @class = "EVTY", value = 1069, name = "SORT_WARNINGS" },
				new syspalvalue { @class = "EVTY", value = 1079, name = "MISSING_COLUMN_STATISTICS" },
				new syspalvalue { @class = "EVTY", value = 1080, name = "MISSING_JOIN_PREDICATE" },
				new syspalvalue { @class = "EVTY", value = 1081, name = "SERVER_MEMORY_CHANGE" },
				new syspalvalue { @class = "EVTY", value = 1082, name = "USERCONFIGURABLE_0" },
				new syspalvalue { @class = "EVTY", value = 1083, name = "USERCONFIGURABLE_1" },
				new syspalvalue { @class = "EVTY", value = 1084, name = "USERCONFIGURABLE_2" },
				new syspalvalue { @class = "EVTY", value = 1085, name = "USERCONFIGURABLE_3" },
				new syspalvalue { @class = "EVTY", value = 1086, name = "USERCONFIGURABLE_4" },
				new syspalvalue { @class = "EVTY", value = 1087, name = "USERCONFIGURABLE_5" },
				new syspalvalue { @class = "EVTY", value = 1088, name = "USERCONFIGURABLE_6" },
				new syspalvalue { @class = "EVTY", value = 1089, name = "USERCONFIGURABLE_7" },
				new syspalvalue { @class = "EVTY", value = 1090, name = "USERCONFIGURABLE_8" },
				new syspalvalue { @class = "EVTY", value = 1091, name = "USERCONFIGURABLE_9" },
				new syspalvalue { @class = "EVTY", value = 1092, name = "DATA_FILE_AUTO_GROW" },
				new syspalvalue { @class = "EVTY", value = 1093, name = "LOG_FILE_AUTO_GROW" },
				new syspalvalue { @class = "EVTY", value = 1094, name = "DATA_FILE_AUTO_SHRINK" },
				new syspalvalue { @class = "EVTY", value = 1095, name = "LOG_FILE_AUTO_SHRINK" },
				new syspalvalue { @class = "EVTY", value = 1102, name = "AUDIT_DATABASE_SCOPE_GDR_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1103, name = "AUDIT_SCHEMA_OBJECT_GDR_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1104, name = "AUDIT_ADDLOGIN_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1105, name = "AUDIT_LOGIN_GDR_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1106, name = "AUDIT_LOGIN_CHANGE_PROPERTY_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1107, name = "AUDIT_LOGIN_CHANGE_PASSWORD_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1108, name = "AUDIT_ADD_LOGIN_TO_SERVER_ROLE_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1109, name = "AUDIT_ADD_DB_USER_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1110, name = "AUDIT_ADD_MEMBER_TO_DB_ROLE_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1111, name = "AUDIT_ADD_ROLE_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1112, name = "AUDIT_APP_ROLE_CHANGE_PASSWORD_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1114, name = "AUDIT_SCHEMA_OBJECT_ACCESS_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1115, name = "AUDIT_BACKUP_RESTORE_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1116, name = "AUDIT_DBCC_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1117, name = "AUDIT_CHANGE_AUDIT_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1119, name = "OLEDB_CALL_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1120, name = "OLEDB_QUERYINTERFACE_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1121, name = "OLEDB_DATAREAD_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1122, name = "SHOWPLAN_XML" },
				new syspalvalue { @class = "EVTY", value = 1125, name = "DEPRECATION_ANNOUNCEMENT" },
				new syspalvalue { @class = "EVTY", value = 1126, name = "DEPRECATION_FINAL_SUPPORT" },
				new syspalvalue { @class = "EVTY", value = 1127, name = "EXCHANGE_SPILL_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1128, name = "AUDIT_DATABASE_MANAGEMENT_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1129, name = "AUDIT_DATABASE_OBJECT_MANAGEMENT_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1130, name = "AUDIT_DATABASE_PRINCIPAL_MANAGEMENT_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1131, name = "AUDIT_SCHEMA_OBJECT_MANAGEMENT_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1132, name = "AUDIT_SERVER_PRINCIPAL_IMPERSONATION_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1133, name = "AUDIT_DATABASE_PRINCIPAL_IMPERSONATION_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1134, name = "AUDIT_SERVER_OBJECT_TAKE_OWNERSHIP_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1135, name = "AUDIT_DATABASE_OBJECT_TAKE_OWNERSHIP_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1137, name = "BLOCKED_PROCESS_REPORT" },
				new syspalvalue { @class = "EVTY", value = 1146, name = "SHOWPLAN_XML_STATISTICS_PROFILE" },
				new syspalvalue { @class = "EVTY", value = 1148, name = "DEADLOCK_GRAPH" },
				new syspalvalue { @class = "EVTY", value = 1150, name = "TRACE_FILE_CLOSE" },
				new syspalvalue { @class = "EVTY", value = 1152, name = "AUDIT_CHANGE_DATABASE_OWNER" },
				new syspalvalue { @class = "EVTY", value = 1153, name = "AUDIT_SCHEMA_OBJECT_TAKE_OWNERSHIP_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1155, name = "FT_CRAWL_STARTED" },
				new syspalvalue { @class = "EVTY", value = 1156, name = "FT_CRAWL_STOPPED" },
				new syspalvalue { @class = "EVTY", value = 1157, name = "FT_CRAWL_ABORTED" },
				new syspalvalue { @class = "EVTY", value = 1162, name = "USER_ERROR_MESSAGE" },
				new syspalvalue { @class = "EVTY", value = 1164, name = "OBJECT_ALTERED" },
				new syspalvalue { @class = "EVTY", value = 1166, name = "SQL_STMTRECOMPILE" },
				new syspalvalue { @class = "EVTY", value = 1167, name = "DATABASE_MIRRORING_STATE_CHANGE" },
				new syspalvalue { @class = "EVTY", value = 1168, name = "SHOWPLAN_XML_FOR_QUERY_COMPILE" },
				new syspalvalue { @class = "EVTY", value = 1169, name = "SHOWPLAN_ALL_FOR_QUERY_COMPILE" },
				new syspalvalue { @class = "EVTY", value = 1170, name = "AUDIT_SERVER_SCOPE_GDR_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1171, name = "AUDIT_SERVER_OBJECT_GDR_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1172, name = "AUDIT_DATABASE_OBJECT_GDR_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1173, name = "AUDIT_SERVER_OPERATION_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1175, name = "AUDIT_SERVER_ALTER_TRACE_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1176, name = "AUDIT_SERVER_OBJECT_MANAGEMENT_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1177, name = "AUDIT_SERVER_PRINCIPAL_MANAGEMENT_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1178, name = "AUDIT_DATABASE_OPERATION_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1180, name = "AUDIT_DATABASE_OBJECT_ACCESS_EVENT" },
				new syspalvalue { @class = "EVTY", value = 1194, name = "OLEDB_PROVIDER_INFORMATION" },
				new syspalvalue { @class = "EVTY", value = 1195, name = "MOUNT_TAPE" },
				new syspalvalue { @class = "EVTY", value = 1196, name = "ASSEMBLY_LOAD" },
				new syspalvalue { @class = "EVTY", value = 1198, name = "XQUERY_STATIC_TYPE" },
				new syspalvalue { @class = "EVTY", value = 1199, name = "QN__SUBSCRIPTION" },
				new syspalvalue { @class = "EVTY", value = 1200, name = "QN__PARAMETER_TABLE" },
				new syspalvalue { @class = "EVTY", value = 1201, name = "QN__TEMPLATE" },
				new syspalvalue { @class = "EVTY", value = 1202, name = "QN__DYNAMICS" },
				new syspalvalue { @class = "EVTY", value = 1212, name = "BITMAP_WARNING" },
				new syspalvalue { @class = "EVTY", value = 1213, name = "DATABASE_SUSPECT_DATA_PAGE" },
				new syspalvalue { @class = "EVTY", value = 1214, name = "CPU_THRESHOLD_EXCEEDED" },
				new syspalvalue { @class = "EVTY", value = 1235, name = "AUDIT_FULLTEXT" },
				new syspalvalue { @class = "EVTY", value = 10001, name = "DDL_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10002, name = "DDL_SERVER_LEVEL_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10003, name = "DDL_ENDPOINT_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10004, name = "DDL_DATABASE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10005, name = "DDL_SERVER_SECURITY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10006, name = "DDL_LOGIN_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10007, name = "DDL_GDR_SERVER_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10008, name = "DDL_AUTHORIZATION_SERVER_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10009, name = "DDL_CREDENTIAL_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10010, name = "DDL_SERVICE_MASTER_KEY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10011, name = "DDL_EXTENDED_PROCEDURE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10012, name = "DDL_LINKED_SERVER_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10013, name = "DDL_LINKED_SERVER_LOGIN_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10014, name = "DDL_MESSAGE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10015, name = "DDL_REMOTE_SERVER_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10016, name = "DDL_DATABASE_LEVEL_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10017, name = "DDL_TABLE_VIEW_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10018, name = "DDL_TABLE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10019, name = "DDL_VIEW_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10020, name = "DDL_INDEX_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10021, name = "DDL_STATISTICS_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10022, name = "DDL_SYNONYM_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10023, name = "DDL_FUNCTION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10024, name = "DDL_PROCEDURE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10025, name = "DDL_TRIGGER_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10026, name = "DDL_EVENT_NOTIFICATION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10027, name = "DDL_ASSEMBLY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10028, name = "DDL_TYPE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10029, name = "DDL_DATABASE_SECURITY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10030, name = "DDL_CERTIFICATE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10031, name = "DDL_USER_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10032, name = "DDL_ROLE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10033, name = "DDL_APPLICATION_ROLE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10034, name = "DDL_SCHEMA_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10035, name = "DDL_GDR_DATABASE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10036, name = "DDL_AUTHORIZATION_DATABASE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10037, name = "DDL_SYMMETRIC_KEY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10038, name = "DDL_ASYMMETRIC_KEY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10039, name = "DDL_CRYPTO_SIGNATURE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10040, name = "DDL_MASTER_KEY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10041, name = "DDL_SSB_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10042, name = "DDL_MESSAGE_TYPE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10043, name = "DDL_CONTRACT_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10044, name = "DDL_QUEUE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10045, name = "DDL_SERVICE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10046, name = "DDL_ROUTE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10047, name = "DDL_REMOTE_SERVICE_BINDING_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10048, name = "DDL_XML_SCHEMA_COLLECTION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10049, name = "DDL_PARTITION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10050, name = "DDL_PARTITION_FUNCTION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10051, name = "DDL_PARTITION_SCHEME_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10052, name = "DDL_DEFAULT_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10053, name = "DDL_EXTENDED_PROPERTY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10054, name = "DDL_FULLTEXT_CATALOG_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10055, name = "DDL_PLAN_GUIDE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10056, name = "DDL_RULE_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10057, name = "DDL_EVENT_SESSION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10058, name = "DDL_RESOURCE_GOVERNOR_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10059, name = "DDL_RESOURCE_POOL" },
				new syspalvalue { @class = "EVTY", value = 10060, name = "DDL_WORKLOAD_GROUP" },
				new syspalvalue { @class = "EVTY", value = 10061, name = "DDL_CRYPTOGRAPHIC_PROVIDER_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10062, name = "DDL_DATABASE_ENCRYPTION_KEY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10063, name = "DDL_BROKER_PRIORITY_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10064, name = "DDL_SERVER_AUDIT_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10065, name = "DDL_SERVER_AUDIT_SPECIFICATION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10066, name = "DDL_DATABASE_AUDIT_SPECIFICATION_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 10067, name = "DDL_FULLTEXT_STOPLIST_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 11000, name = "TRC_ALL_EVENTS" },
				new syspalvalue { @class = "EVTY", value = 11002, name = "TRC_DATABASE" },
				new syspalvalue { @class = "EVTY", value = 11003, name = "TRC_ERRORS_AND_WARNINGS" },
				new syspalvalue { @class = "EVTY", value = 11004, name = "TRC_LOCKS" },
				new syspalvalue { @class = "EVTY", value = 11005, name = "TRC_OBJECTS" },
				new syspalvalue { @class = "EVTY", value = 11006, name = "TRC_PERFORMANCE" },
				new syspalvalue { @class = "EVTY", value = 11008, name = "TRC_SECURITY_AUDIT" },
				new syspalvalue { @class = "EVTY", value = 11009, name = "TRC_SERVER" },
				new syspalvalue { @class = "EVTY", value = 11011, name = "TRC_STORED_PROCEDURES" },
				new syspalvalue { @class = "EVTY", value = 11013, name = "TRC_TSQL" },
				new syspalvalue { @class = "EVTY", value = 11014, name = "TRC_USER_CONFIGURABLE" },
				new syspalvalue { @class = "EVTY", value = 11015, name = "TRC_OLEDB" },
				new syspalvalue { @class = "EVTY", value = 11017, name = "TRC_FULL_TEXT" },
				new syspalvalue { @class = "EVTY", value = 11018, name = "TRC_DEPRECATION" },
				new syspalvalue { @class = "EVTY", value = 11020, name = "TRC_CLR" },
				new syspalvalue { @class = "EVTY", value = 11021, name = "TRC_QUERY_NOTIFICATIONS" },
				new syspalvalue { @class = "FITS", value = 0, name = "OFF" },
				new syspalvalue { @class = "FITS", value = 1, name = "MANUAL" },
				new syspalvalue { @class = "FITS", value = 3, name = "AUTO" },
				new syspalvalue { @class = "FKRA", value = 0, name = "NO_ACTION" },
				new syspalvalue { @class = "FKRA", value = 1, name = "CASCADE" },
				new syspalvalue { @class = "FKRA", value = 2, name = "SET_NULL" },
				new syspalvalue { @class = "FKRA", value = 3, name = "SET_DEFAULT" },
				new syspalvalue { @class = "IDXT", value = 0, name = "HEAP" },
				new syspalvalue { @class = "IDXT", value = 1, name = "CLUSTERED" },
				new syspalvalue { @class = "IDXT", value = 2, name = "NONCLUSTERED" },
				new syspalvalue { @class = "IDXT", value = 3, name = "XML" },
				new syspalvalue { @class = "IDXT", value = 4, name = "SPATIAL" },
				new syspalvalue { @class = "ITTY", value = 201, name = "QUEUE_MESSAGES" },
				new syspalvalue { @class = "ITTY", value = 202, name = "XML_INDEX_NODES" },
				new syspalvalue { @class = "ITTY", value = 203, name = "FULLTEXT_CATALOG_FREELIST" },
				new syspalvalue { @class = "ITTY", value = 204, name = "FULLTEXT_INDEX_MAP" },
				new syspalvalue { @class = "ITTY", value = 205, name = "QUERY_NOTIFICATION" },
				new syspalvalue { @class = "ITTY", value = 206, name = "SERVICE_BROKER_MAP" },
				new syspalvalue { @class = "ITTY", value = 207, name = "EXTENDED_INDEXES" },
				new syspalvalue { @class = "ITTY", value = 208, name = "FILESTREAM_TOMBSTONE" },
				new syspalvalue { @class = "ITTY", value = 209, name = "CHANGE_TRACKING" },
				new syspalvalue { @class = "ITTY", value = 210, name = "TRACKED_COMMITTED_TRANSACTIONS" },
				new syspalvalue { @class = "ITTY", value = 211, name = "FULLTEXT_AVDL" },
				new syspalvalue { @class = "ITTY", value = 212, name = "FULLTEXT_COMP_FRAGMENT" },
				new syspalvalue { @class = "ITTY", value = 213, name = "FULLTEXT_DOCID_STATUS" },
				new syspalvalue { @class = "ITTY", value = 214, name = "FULLTEXT_INDEXED_DOCID" },
				new syspalvalue { @class = "ITTY", value = 215, name = "FULLTEXT_DOCID_FILTER" },
				new syspalvalue { @class = "ITTY", value = 216, name = "FULLTEXT_DOCID_MAP" },
				new syspalvalue { @class = "ITTY", value = 217, name = "FULLTEXT_THESAURUS_METADATA_TABLE" },
				new syspalvalue { @class = "ITTY", value = 218, name = "FULLTEXT_THESAURUS_STATE_TABLE" },
				new syspalvalue { @class = "ITTY", value = 219, name = "FULLTEXT_THESAURUS_PHRASE_TABLE" },
				new syspalvalue { @class = "LEOP", value = 0, name = "TABLE" },
				new syspalvalue { @class = "LEOP", value = 1, name = "DISABLE" },
				new syspalvalue { @class = "LEOP", value = 2, name = "AUTO" },
				new syspalvalue { @class = "LRWT", value = 0, name = "NOTHING" },
				new syspalvalue { @class = "LRWT", value = 1, name = "CHECKPOINT" },
				new syspalvalue { @class = "LRWT", value = 2, name = "LOG_BACKUP" },
				new syspalvalue { @class = "LRWT", value = 3, name = "ACTIVE_BACKUP_OR_RESTORE" },
				new syspalvalue { @class = "LRWT", value = 4, name = "ACTIVE_TRANSACTION" },
				new syspalvalue { @class = "LRWT", value = 5, name = "DATABASE_MIRRORING" },
				new syspalvalue { @class = "LRWT", value = 6, name = "REPLICATION" },
				new syspalvalue { @class = "LRWT", value = 7, name = "DATABASE_SNAPSHOT_CREATION" },
				new syspalvalue { @class = "LRWT", value = 8, name = "LOG_SCAN" },
				new syspalvalue { @class = "LRWT", value = 9, name = "OTHER TRANSIENT" },
				new syspalvalue { @class = "SPRF", value = 1, name = "ALL_RESULTS" },
				new syspalvalue { @class = "SPRF", value = 2, name = "ROWSETS_ONLY" },
				new syspalvalue { @class = "SPRF", value = 3, name = "NONE" },
				new syspalvalue { @class = "SPRS", value = 0, name = "NONE" },
				new syspalvalue { @class = "SPRS", value = 1, name = "STANDARD" },
				new syspalvalue { @class = "SPRS", value = 2, name = "DEFAULT" },
				new syspalvalue { @class = "SPSL", value = 0, name = "WINDOWS" },
				new syspalvalue { @class = "SPSL", value = 64, name = "MIXED" },
				new syspalvalue { @class = "SRCL", value = 14, name = "CRYPTOGRAPHIC PROVIDER" },
				new syspalvalue { @class = "UNCL", value = 0, name = "DATABASE" },
				new syspalvalue { @class = "UNCL", value = 1, name = "OBJECT_OR_COLUMN" },
				new syspalvalue { @class = "UNCL", value = 2, name = "PARAMETER" },
				new syspalvalue { @class = "UNCL", value = 3, name = "SCHEMA" },
				new syspalvalue { @class = "UNCL", value = 4, name = "DATABASE_PRINCIPAL" },
				new syspalvalue { @class = "UNCL", value = 5, name = "ASSEMBLY" },
				new syspalvalue { @class = "UNCL", value = 6, name = "TYPE" },
				new syspalvalue { @class = "UNCL", value = 7, name = "INDEX" },
				new syspalvalue { @class = "UNCL", value = 8, name = "TYPE_COLUMN" },
				new syspalvalue { @class = "UNCL", value = 9, name = "STATISTICS" },
				new syspalvalue { @class = "UNCL", value = 10, name = "XML_SCHEMA_COLLECTION" },
				new syspalvalue { @class = "UNCL", value = 11, name = "XML_COMPONENT" },
				new syspalvalue { @class = "UNCL", value = 12, name = "DATABASE_DDL_TRIGGER" },
				new syspalvalue { @class = "UNCL", value = 13, name = "SERVER_DDL_TRIGGER" },
				new syspalvalue { @class = "UNCL", value = 15, name = "MESSAGE_TYPE" },
				new syspalvalue { @class = "UNCL", value = 16, name = "SERVICE_CONTRACT" },
				new syspalvalue { @class = "UNCL", value = 17, name = "SERVICE" },
				new syspalvalue { @class = "UNCL", value = 18, name = "REMOTE_SERVICE_BINDING" },
				new syspalvalue { @class = "UNCL", value = 19, name = "ROUTE" },
				new syspalvalue { @class = "UNCL", value = 20, name = "DATASPACE" },
				new syspalvalue { @class = "UNCL", value = 21, name = "PARTITION_FUNCTION" },
				new syspalvalue { @class = "UNCL", value = 22, name = "DATABASE_FILE" },
				new syspalvalue { @class = "UNCL", value = 23, name = "FULLTEXT_CATALOG" },
				new syspalvalue { @class = "UNCL", value = 24, name = "SYMMETRIC_KEYS" },
				new syspalvalue { @class = "UNCL", value = 25, name = "CERTIFICATE" },
				new syspalvalue { @class = "UNCL", value = 26, name = "ASYMMETRIC_KEY" },
				new syspalvalue { @class = "UNCL", value = 27, name = "PLAN_GUIDE" },
				new syspalvalue { @class = "UNCL", value = 28, name = "CONVERSATION_PRIORITY" },
				new syspalvalue { @class = "UNCL", value = 29, name = "FULLTEXT_STOPLIST" },
				new syspalvalue { @class = "UNCL", value = 30, name = "AUDIT_SPECIFICATION" },
				new syspalvalue { @class = "UNCL", value = 100, name = "SERVER" },
				new syspalvalue { @class = "UNCL", value = 101, name = "SERVER_PRINCIPAL" },
				new syspalvalue { @class = "UNCL", value = 102, name = "LINKED_SERVER" },
				new syspalvalue { @class = "UNCL", value = 103, name = "LINKED_LOGIN" },
				new syspalvalue { @class = "UNCL", value = 104, name = "REMOTE_LOGIN" },
				new syspalvalue { @class = "UNCL", value = 105, name = "ENDPOINT" },
				new syspalvalue { @class = "UNCL", value = 106, name = "CERTIFICATE" },
				new syspalvalue { @class = "XITY", value = 80, name = "PATH" },
				new syspalvalue { @class = "XITY", value = 82, name = "PROPERTY" },
				new syspalvalue { @class = "XITY", value = 86, name = "VALUE" }
			};
		}
	}
}